apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ea2-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-static-ip2
spec:
  rules:
    - http:
        paths:
          - path: /auth/*
            backend:
              serviceName: auth-ms-service
              servicePort: 8080

          - path: /questions/*
            backend:
              serviceName: question-ms-service
              servicePort: 8080


          - path: /users/*
            backend:
              serviceName: user-ms-service
              servicePort: 8080

          - path: /answers/*
            backend:
              serviceName: answer-ms-service
              servicePort: 8080

          - path: /comments/*
            backend:
              serviceName: comment-ms-service
              servicePort: 8080
