apiVersion: v1
kind: ConfigMap
metadata:
  name: services-global
  namespace: default
data:
  KAFKA_BOOTSTRAP_SERVERS: "34.70.124.18:31090,34.68.183.147:31090,35.223.233.128:31090"
  SERVICE_SECRET: "service-secret"

  # SERVICE DISCOVERY
  QUESTIONS_SERVICE: "question-ms-service"
  AUTHENTICATE_SERVICE: "auth-ms-service.default.svc.cluster.local:8080"
